In [4]:
def jacobi_symbol(a, n):
    """Вычисление символа Якоби (a/n)"""
    if n <= 0 or n % 2 == 0:
        return 0
    j = 1
    if a < 0:
        a = -a
        if n % 4 == 3:
            j = -j
    while a != 0:
        while a % 2 == 0:
            a = a // 2
            if n % 8 in [3, 5]:
                j = -j
        a, n = n, a
        if a % 4 == 3 and n % 4 == 3:
            j = -j
        a = a % n
    if n == 1:
        return j
    else:
        return 0

def inverse_mod(a, m):
    """Нахождение обратного элемента для 'a' по модулю 'm'"""
    m0, x0, x1 = m, 0, 1
    while a > 1:
        q = a // m
        m, a = a % m, m
        x0, x1 = x1 - q * x0, x0
    return x1 + m0 if x1 < 0 else x1

def quadratic_residue_modulo(d, m):
    """Решение квадратичного сравнения x^2 ≡ d (mod m)"""
    solutions = []
    if jacobi_symbol(d, m) == -1:
        return solutions  # Нет решений
    for x in range(m):
        if (x*x - d) % m == 0:
            solutions.append(x)
    return solutions

# Пример использования:
d = 4
m = 21
print(f"Решения x^2 ≡ {d} (mod {m}): {quadratic_residue_modulo(d, m)}")


Решения x^2 ≡ 4 (mod 21): [2, 5, 16, 19]


## Задание 1
Числа Мерсена — это числа вида $(M_n = 2^n - 1)$, где n — натуральное число. Чтобы число Мерсена было простым, n также должно быть простым числом, однако не каждое число вида $(M_n = 2^n - 1)$, где n простое, является простым числом. Приведу пример пяти простых чисел Мерсена.

**Примеры простых чисел Мерсена:**
1. $(n = 2)$, $(M_2 = 2^2 - 1 = 3)$
2. $(n = 3)$, $(M_3 = 2^3 - 1 = 7)$
3. $(n = 5)$, $(M_5 = 2^5 - 1 = 31)$
4. $(n = 7)$, $(M_7 = 2^7 - 1 = 127)$
5. $(n = 13)$, $(M_{13} = 2^{13} - 1 = 8191)$

## Задание 2

Числа Ферма — это числа вида $(F_n = 2^{2^n} + 1)$, где n — целое неотрицательное число. Пьер Ферма выдвинул гипотезу, что все такие числа являются простыми, однако позже было доказано, что это не так для всех n. 

**Примеры простых чисел Ферма:**

1. $(F_0 = 2^{2^0} + 1 = 2^1 + 1 = 3)$
2. $(F_1 = 2^{2^1} + 1 = 2^2 + 1 = 5)$
3. $(F_2 = 2^{2^2} + 1 = 2^4 + 1 = 17)$
4. $(F_3 = 2^{2^3} + 1 = 2^8 + 1 = 257)$


## Задание 3

Тест Ферма — это простой способ проверки числа на простоту, который опирается на малую теорему Ферма. Согласно малой теореме Ферма, если p — простое число и a — целое число, не делящееся на p, то $(a^{p-1} \equiv 1 \mod p)$.

Для проведения теста Ферма для заданных чисел, выберем a так, чтобы 1 < a < p (чаще всего используют a = 2), и вычислим $(a^{p-1} \mod p)$. Если результат не равен 1, число не является простым. Если результат равен 1, число может быть простым, но для полной уверенности требуются дополнительные проверки, так как существуют составные числа, которые также удовлетворяют этому условию (псевдопростые числа).

Проведем тест для чисел 23, 41, 15, 35 и 561 с a = 2.

**Расчеты:**

1. Для p = 23, проверим $(2^{22} \mod 23)$
2. Для p = 41, проверим $(2^{40} \mod 41)$
3. Для p = 15, проверим $(2^{14} \mod 15)$
4. Для p = 35, проверим $(2^{34} \mod 35)$
5. Для p = 561, проверим $(2^{560} \mod 561)$

Давайте выполним эти расчеты.

Результаты теста Ферма для данных чисел следующие:

1. Для p = 23, $(2^{22} \mod 23 = 1)$
2. Для p = 41, $(2^{40} \mod 41 = 1)$
3. Для p = 15, $(2^{14} \mod 15 = 4)$
4. Для p = 35, $(2^{34} \mod 35 = 9)$
5. Для p = 561, $(2^{560} \mod 561 = 1)$

Из результатов видно, что числа 23 и 41 проходят тест Ферма, что соответствует их простоте. Числа 15 и 35 не проходят тест Ферма, что подтверждает их составной характер. Однако число 561 также проходит тест Ферма, возвращая результат 1, несмотря на то, что оно является составным. Это делает 561 псевдопростым числом по основанию 2.

Последнее число, 561, известно как число Кармайкла. Числа Кармайкла — это особый класс составных чисел, которые удовлетворяют условию малой теоремы Ферма $(a^{p-1} \equiv 1 \mod p)$ для всех a, взаимно простых с p, и поэтому они могут вводить в заблуждение тесты простоты, основанные на малой теореме Ферма.
561 = 3 * 11 * 17

## Задание 4
Испытание квадратным корнем — это метод проверки числа на простоту, который заключается в поиске делителей числа в пределах, не превышающих квадратный корень из этого числа. Если в этом диапазоне не найдено никаких делителей, число считается простым. В противном случае оно составное.

Произведем испытание квадратным корнем для чисел 23, 41, 15, 35 и 561.

**Алгоритм проверки:**
1. Вычислить квадратный корень из числа.
2. Проверить все целые числа от 2 до округленного вверх значения квадратного корня на деление проверяемого числа без остатка.
3. Если делитель найден, число составное; если нет — простое.

Результаты испытания квадратным корнем для данных чисел следующие:

- 23: Простое число
- 41: Простое число
- 15: Составное число
- 35: Составное число
- 561: Составное число

Эти результаты подтверждают, что 23 и 41 являются простыми числами, так как для них не было найдено никаких делителей в пределах до квадратного корня из числа. Числа 15, 35 и 561 являются составными, поскольку для них были найдены делители, не равные 1 и самому числу.

In [5]:
import math

# Числа для проверки
numbers = [23, 41, 15, 35, 561]

# Функция для проверки числа на простоту методом испытания квадратным корнем
def is_prime_sqrt_test(n):
    if n <= 1:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Проведение проверки для каждого числа
prime_test_results = {n: is_prime_sqrt_test(n) for n in numbers}

prime_test_results


{23: True, 41: True, 15: False, 35: False, 561: False}

## Задание 5
Тест Миллера-Рабина — это вероятностный тест простоты, который используется для определения, является ли данное число простым. Он основан на свойствах простых чисел и предполагает выполнение определенных условий для числа n, чтобы считаться простым. Этот тест может дать два типа результатов: "составное" с абсолютной уверенностью и "вероятно простое", где вероятность ошибки в принятии составного числа за простое снижается с увеличением количества раундов теста.

Для проведения теста Миллера-Рабина для чисел 23, 41, 15, 35 и 561, я выполню вычисления и предоставлю результаты. Поскольку это вероятностный тест, для чисел, которые он определит как "вероятно простые", будет использовано несколько раундов для увеличения достоверности результатов.

**Результаты теста Миллера-Рабина**

- 23: Вероятно простое (тест подтверждает простоту)
- 41: Вероятно простое (тест подтверждает простоту)
- 15: Составное
- 35: Составное
- 561: Составное

**Шаги**

1. Проверить, не является ли число n четным или меньше 2, так как все четные числа, кроме 2, являются составными.
2. Найти d и r такие, что $(n - 1 = d \cdot 2^r)$, где d нечетно. Это представление n - 1 как произведения степени двойки на нечетное число.
3. Провести заданное количество раундов тестирования. Для каждого раунда:
   - Выбрать случайное число a в интервале [2, n - 2].
   - Вычислить $(x = a^d \mod n)$. Если x = 1 или x = n - 1, перейти к следующему раунду.
   - Повторять возведение x в квадрат $((x^2 \mod n))$ r - 1 раз. Если в какой-то момент получается n - 1, перейти к следующему раунду. Если доходит до конца цикла и n - 1 не встретилось, вернуть "составное".

В этой реализации функция `miller_rabin` принимает два параметра: проверяемое число `n` и количество раундов `k`, которое определяет точность и вероятность правильного определения простоты числа. Чем больше раундов, тем выше точность, но и больше времени требуется на вычисления.

In [8]:
import random

def miller_rabin(n, k = 5):
    if n == 2 or n == 3:
        return True
    if n <= 1 or n % 2 == 0:
        return False

    # Найти d, r такие, что d * 2^r = n - 1
    r, d = 0, n - 1
    while d % 2 == 0:
        r += 1
        d //= 2

    # Провести k раундов тестирования
    for _ in range(k):
        a = random.randrange(2, n - 1)
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue

        for _ in range(r - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                break
        else:
            return False
    return True

# Проведение теста Миллера-Рабина для каждого числа
miller_rabin_results = {n: miller_rabin(n) for n in numbers}

miller_rabin_results

{23: True, 41: True, 15: False, 35: False, 561: False}

## Задание 6
Метод Ферма для разложения на множители основан на поиске таких целых чисел x и y, что $(n = x^2 - y^2 = (x + y)(x - y))$, где n — данное нечетное составное число, которое необходимо разложить. Этот метод наиболее эффективен, когда n является произведением двух простых чисел, близких друг к другу по значению.

Алгоритм:
1. Начать с $(x = \lceil \sqrt{n} \rceil)$, где $(\lceil \cdot \rceil)$ обозначает округление до ближайшего большего целого числа.
2. Вычислить $(y^2 = x^2 - n)$. Если $(y^2)$ является полным квадратом, то n можно разложить на множители как $(n = (x + y)(x - y))$.
3. Увеличить \(x\) на 1 и повторить шаг 2 до тех пор, пока не будет найдено разложение.

Реализуем этот метод на Python и применим его к числам 483, 1207, 561, 1219.

Разложение на множители методом Ферма для данных чисел:

- 483 = 23 × 21
- 1207 = 71 × 17
- 561 = 33 × 17
- 1219 = 53 × 23

In [9]:
import math

def fermat_factorization(n):
    x = math.ceil(math.sqrt(n))
    while True:
        y2 = x**2 - n
        y = math.sqrt(y2)
        if y.is_integer():
            return (int(x + y), int(x - y))
        x += 1

# Применяем метод Ферма к заданным числам
numbers = [483, 1207, 561, 1219]
factorizations = {n: fermat_factorization(n) for n in numbers}

factorizations


{483: (23, 21), 1207: (71, 17), 561: (33, 17), 1219: (53, 23)}

## Задание 7
Метод Полларда (p-1) для разложения на множители основан на предположении, что для составного числа n, существует делитель p, такой что p-1 имеет только малые простые делители. Идея метода заключается в том, что если p является делителем n, и a — случайно выбранное число, не делящееся на p, то с большой вероятностью $(\gcd(a^{k!} - 1, n))$ будет ненулевым делителем n для некоторого k.

Алгоритм:
1. Выбрать начальное значение a > 1 (обычно a = 2).
2. Выбрать границу B для простых чисел p, которые будут использоваться.
3. Вычислить $(a^{B!} \mod n)$ посредством последовательного возведения в степень, используя малые простые числа до B.
4. Вычислить $(\gcd(a^{B!} - 1, n))$. Если результат больше 1, это будет делитель n.

Реализуем этот метод на Python и применим его к числам 483, 1207, 561, 1219, используя простую границу B.

Применение метода (p-1) Полларда для разложения на множители к указанным числам с базовой границей B=10 дало следующие результаты:

- 483: найден делитель 21
- 1207: делитель не найден
- 561: делитель не найден
- 1219: делитель не найден

Для числа 483 метод успешно нашел нетривиальный делитель. Однако для остальных чисел делители не были найдены при выбранной границе B=10. Это может означать, что для успешного разложения этих чисел требуется использовать более высокое значение B, так как возможно, что p-1 для их делителей p содержит более крупные простые числа.

In [10]:
from math import gcd

def pollard_p_minus_1(n, B=10):
    a = 2  # Начальное значение для a
    for j in range(2, B+1):
        a = pow(a, j, n)
    d = gcd(a-1, n)
    if 1 < d < n:  # Нашли нетривиальный делитель
        return d
    else:
        return None  # Делитель не найден или нужно увеличить B

# Применяем метод (p-1) Полларда к заданным числам
numbers = [483, 1207, 561, 1219]
pollard_results = {n: pollard_p_minus_1(n) for n in numbers}

pollard_results


{483: 21, 1207: None, 561: None, 1219: None}